apiVersion: platform.teknologi.io/v1alpha1
kind: XStorageAccount
metadata:
  name: sa-matrix-restapi-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    kratix.io/promise-name: storage-account
    kratix.io/resource-name: matrix-restapi-sa
spec:
  appName: matrix-restapi
  environment: dev
  storageAccountName: tekmatrixrestapidevsa
  location: westeurope
  resourceGroupName: teknologi-eur1-prd-platform-rg
