apiVersion: platform.teknologi.io/v1alpha1
kind: XKeyVault
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: kv-matrix-onb-kubectl-dev
spec:
  appName: matrix-onb-kubectl
  environment: dev
  location: westeurope
  resourceGroupName: teknologi-eur1-dev-matrix-onb-kubectl-rg
  tenantId: 99f9af3a-fd8b-41ec-b487-483a0c562b5c
