apiVersion: platform.teknologi.io/v1alpha1
kind: XNamespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: matrix-onb-kubectl-dev
spec:
  environment: dev
  namespaceName: matrix-onb-kubectl-dev
  networkVisibility: private
