apiVersion: platform.teknologi.io/v1alpha1
kind: XNamespace
metadata:
  name: finding4-1007-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    kratix.io/promise-name: namespace
    kratix.io/resource-name: finding4-1007-a
spec:
  namespaceName: finding4-1007-dev
  environment: dev
  networkVisibility: private
