apiVersion: platform.teknologi.io/v1alpha1
kind: XKeyVault
metadata:
  name: kv-app-a-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    kratix.io/promise-name: keyvault
    kratix.io/resource-name: app-a-dev-kv
spec:
  appName: app-a
  tenantId: 99f9af3a-fd8b-41ec-b487-483a0c562b5c
  environment: dev
  location: westeurope
  resourceGroupName: teknologi-eur1-prd-platform-rg
