apiVersion: platform.teknologi.io/v1alpha1
kind: XStorageAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: sa-app-d-dev
spec:
  appName: app-d
  environment: dev
  location: westeurope
  resourceGroupName: teknologi-eur1-dev-app-d-rg
  storageAccountName: tekappddevsa
