apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: xkeyvaults.platform.teknologi.io
spec:
  group: platform.teknologi.io
  names:
    kind: XKeyVault
    plural: xkeyvaults
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              appName:
                type: string
              environment:
                default: dev
                enum:
                - dev
                - tst
                - acc
                - prd
                type: string
              location:
                default: westeurope
                type: string
              resourceGroupName:
                type: string
              tenantId:
                description: Azure tenant ID
                type: string
            required:
            - appName
            - environment
            - resourceGroupName
            type: object
          status:
            properties:
              vaultName:
                type: string
              vaultUri:
                type: string
            type: object
        type: object
    served: true
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    provider: azure
  name: xkeyvault-azure
spec:
  compositeTypeRef:
    apiVersion: platform.teknologi.io/v1alpha1
    kind: XKeyVault
  mode: Pipeline
  pipeline:
  - functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - base:
          apiVersion: keyvault.azure.upbound.io/v1beta2
          kind: Vault
          spec:
            forProvider:
              purgeProtectionEnabled: false
              skuName: standard
              softDeleteRetentionDays: 7
            providerConfigRef:
              name: azure-provider
        name: keyvault
        patches:
        - fromFieldPath: spec.tenantId
          toFieldPath: spec.forProvider.tenantId
          type: FromCompositeFieldPath
        - fromFieldPath: spec.location
          policy:
            fromFieldPath: Optional
          toFieldPath: spec.forProvider.location
          type: FromCompositeFieldPath
        - fromFieldPath: spec.resourceGroupName
          policy:
            fromFieldPath: Optional
          toFieldPath: spec.forProvider.resourceGroupName
          type: FromCompositeFieldPath
        - combine:
            strategy: string
            string:
              fmt: kv-%s-%s
            variables:
            - fromFieldPath: spec.appName
            - fromFieldPath: spec.environment
          toFieldPath: metadata.name
          type: CombineFromComposite
        - combine:
            strategy: string
            string:
              fmt: kv-%s-%s
            variables:
            - fromFieldPath: spec.appName
            - fromFieldPath: spec.environment
          toFieldPath: metadata.annotations[crossplane.io/external-name]
          type: CombineFromComposite
        - fromFieldPath: metadata.name
          toFieldPath: status.vaultName
          type: ToCompositeFieldPath
        - fromFieldPath: status.atProvider.vaultUri
          policy:
            fromFieldPath: Optional
          toFieldPath: status.vaultUri
          type: ToCompositeFieldPath
    step: patch-and-transform
