apiVersion: platform.teknologi.io/v1alpha1
kind: XNamespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: approval-1007a-tst
spec:
  environment: tst
  namespaceName: approval-1007a-tst
  networkVisibility: private
