apiVersion: platform.teknologi.io/v1alpha1
kind: XResourceGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: teknologi-eur1-tst-approval-1007a-rg
spec:
  location: westeurope
