apiVersion: platform.teknologi.io/v1alpha1
kind: XStorageAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: sa-matrix-onb-restapi-dev
spec:
  appName: matrix-onb-restapi
  environment: dev
  location: westeurope
  resourceGroupName: teknologi-eur1-dev-matrix-onb-restapi-rg
  storageAccountName: tekmatrixonbrestapidevsa
